### ISSUE TITLE
图片缩放问题

### ISSUE THREAD

**Issue by Overtrued** [qqh0618/PyQt5-YOLOv8#1]
您好， 我的图片是4096x1020的。我检测我的图片 ，图片框就放大了。而且我的框很粗，我尝试调整但是没有效果，您能帮帮我吗。谢谢

**Comment by qqh0618** [comment]
明白了，应该是QLable出了问题，下一版会添加图片自适应qlable尺寸

**Comment by qqh0618** [comment]
经过测试，没有发现问题，请重新描述问题和运行环境，方便解决
